/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Up1RouteImport } from './routes/up1'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrackingRouteImport } from './routes/api/tracking'
import { Route as ApiCreatePixRouteImport } from './routes/api/create-pix'
import { Route as ApiCheckStatusRouteImport } from './routes/api/check-status'
import { Route as AcaiSlugRouteImport } from './routes/acai.$slug'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public.webhook'

const Up1Route = Up1RouteImport.update({
  id: '/up1',
  path: '/up1',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackingRoute = ApiTrackingRouteImport.update({
  id: '/api/tracking',
  path: '/api/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatePixRoute = ApiCreatePixRouteImport.update({
  id: '/api/create-pix',
  path: '/api/create-pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckStatusRoute = ApiCheckStatusRouteImport.update({
  id: '/api/check-status',
  path: '/api/check-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AcaiSlugRoute = AcaiSlugRouteImport.update({
  id: '/acai/$slug',
  path: '/acai/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/success': typeof SuccessRoute
  '/up1': typeof Up1Route
  '/acai/$slug': typeof AcaiSlugRoute
  '/api/check-status': typeof ApiCheckStatusRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/tracking': typeof ApiTrackingRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/success': typeof SuccessRoute
  '/up1': typeof Up1Route
  '/acai/$slug': typeof AcaiSlugRoute
  '/api/check-status': typeof ApiCheckStatusRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/tracking': typeof ApiTrackingRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/success': typeof SuccessRoute
  '/up1': typeof Up1Route
  '/acai/$slug': typeof AcaiSlugRoute
  '/api/check-status': typeof ApiCheckStatusRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/tracking': typeof ApiTrackingRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/success'
    | '/up1'
    | '/acai/$slug'
    | '/api/check-status'
    | '/api/create-pix'
    | '/api/tracking'
    | '/api/public/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/success'
    | '/up1'
    | '/acai/$slug'
    | '/api/check-status'
    | '/api/create-pix'
    | '/api/tracking'
    | '/api/public/webhook'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/success'
    | '/up1'
    | '/acai/$slug'
    | '/api/check-status'
    | '/api/create-pix'
    | '/api/tracking'
    | '/api/public/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  SuccessRoute: typeof SuccessRoute
  Up1Route: typeof Up1Route
  AcaiSlugRoute: typeof AcaiSlugRoute
  ApiCheckStatusRoute: typeof ApiCheckStatusRoute
  ApiCreatePixRoute: typeof ApiCreatePixRoute
  ApiTrackingRoute: typeof ApiTrackingRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/up1': {
      id: '/up1'
      path: '/up1'
      fullPath: '/up1'
      preLoaderRoute: typeof Up1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tracking': {
      id: '/api/tracking'
      path: '/api/tracking'
      fullPath: '/api/tracking'
      preLoaderRoute: typeof ApiTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-pix': {
      id: '/api/create-pix'
      path: '/api/create-pix'
      fullPath: '/api/create-pix'
      preLoaderRoute: typeof ApiCreatePixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-status': {
      id: '/api/check-status'
      path: '/api/check-status'
      fullPath: '/api/check-status'
      preLoaderRoute: typeof ApiCheckStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acai/$slug': {
      id: '/acai/$slug'
      path: '/acai/$slug'
      fullPath: '/acai/$slug'
      preLoaderRoute: typeof AcaiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  SuccessRoute: SuccessRoute,
  Up1Route: Up1Route,
  AcaiSlugRoute: AcaiSlugRoute,
  ApiCheckStatusRoute: ApiCheckStatusRoute,
  ApiCreatePixRoute: ApiCreatePixRoute,
  ApiTrackingRoute: ApiTrackingRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
